
```{r}
packages <- c("here", "janitor", "tidyverse", "sf", "terra", "tmap", "spData", "spDataLarge", "geodata", "kableExtra", "viridisLite")
installed_packages <- packages %in% rownames(installed.packages())
install.packages("spDataLarge", repos = c("https://geocompx.r-universe.dev", "https://cloud.r-project.org"))

if (any(installed_packages == FALSE)) {
  install.packages(packages[!installed_packages])
}

library(here)
library(janitor)
library(tidyverse)
library(sf)
library(kableExtra)

```


```{r}
# the here function pinpoints the exact location of the dam dataset file path
gdw_df = read_csv(here("data", "gdw.csv")) |> 
    # a function of janitor that strips out spaces, punctuation, symbols, and accents to convert columns names into a cleaner format
    clean_names()
```


```{r}
head(gdw_df, 10) |> 
  kable()
tail(gdw_df, 10) |> 
  kable()

print(nrow(gdw_df))
print(ncol(gdw_df))
print(names(gdw_df))
```


```{r}
country_df <- gdw_df[,'country']
country_vec <- gdw_df[["country"]]

gdw_df |> 
  group_by(dam_type) |> 
  summarise(count = n()) |> 
  ungroup()

sub_dam <- gdw_df |> 
  filter(dam_type == "Dam")

gdw_df <- gdw_df |> 
  arrange(year_dam)
  
```


```{r}
gdw_df |> 
  group_by(country) |> 
  summarize(mean_dam_hgt_m = mean(dam_hgt_m, na.rm = TRUE)) |> 
  ungroup() |> 
  ggplot(aes(x = country, mean_dam_hgt_m)) +
    geom_bar(stat = 'identity') + 
    labs(x = "Country",
         y = "Average height of dam (m)") +
    theme_minimal()


gdw_df |> 
  ggplot(aes(x = cap_mcm, y = dam_hgt_m)) +
    geom_point() + 
    labs(x = "Max Storage Capacity (mcm)",
         y = "Dam Height (m)") + 
    theme_minimal()
```